[package]
name = "hopshell"
version = "1.3.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    clearscreen = "1.0.4"
    meval = "0.2"

[build-dependencies]
    winres = "0.1.12"